[package]
name = "fami-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
image = "0.23.14"
num-traits = "0.2"
num-derive = "0.3"